version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - API_KEY=Fy3QGo4YBHyQtkA
    depends_on:
      - db
    networks:
      - my_network
  acme_db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_HOST=acme_db
      - MYSQL_DATABASE=db_api
      - MYSQL_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network

networks:
  my_network:

volumes:
  mysql_data:
